# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
