# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20191003_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.URLField(),
        ),
    ]
